server:
  port: 8081
spring:
  security:
    oauth2:
      client:
        registration:
          booking-sample-client:
            client-id: booking-sample-client
            client-secret: 5ea3fb59-edcc-43b0-94cd-7964e8588ef9
            client-name: Booking Sample Client
            scope: openid, offline_access
            redirect-uri: http://localhost:8081/login/oauth2/code/booking-sample-client
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            provider: keycloak-provider
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8080/auth/realms/BookingSample
